version: "3.9"

services:
  api:
    build: ./api
    container_name: url-api
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=url-db
      - DB_NAME=urlshortener
      - DB_USER=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: url-db
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db_data:/var/lib/postgresql/data